version: '3.8'

services:
  app:
    build: .
    container_name: visa-app
    ports:
      - "80:80"
      - "443:80"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./prisma/prod.db
      - PORT=80
    volumes:
      - ./prisma:/app/prisma
    restart: unless-stopped
    cap_add:
      - NET_BIND_SERVICE
